# This release drafter follows the conventions
# from https://keepachangelog.com

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bug
  - title: ⚠️ Changes
    labels:
      - changed
      - chore
      - style
      - refactor
      - test
      - perf
      - chore
  - title: ⚙️  Build/CI
    labels:
      - ci
      - build
  - title: ⛔️ Deprecated
    labels:
      - deprecated
  - title: 🗑 Removed
    labels:
      - removed
  - title: 🔐 Security
    labels:
      - security
  - title: 📄 Documentation
    labels:
      - docs
      - documentation
  - title: 🧩 Dependency Updates
    labels:
      - deps
      - dependencies
    collapse-after: 5

change-template: '- $TITLE @$AUTHOR ([#$NUMBER](https://github.com/sandialabs/firewheel/pull/$NUMBER))'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
  
exclude-labels:
  - skip-changelog

autolabeler:
  - label: 'feature'
    branch:
      - /(feature|feat)[-\/].+/
    title:
      - /(feature|feat)[:].+/
  - label: 'fix'
    branch:
      - /(fix|bug|bugfix)[-/].+/
    title:
      - /(fix|bug|bugfix)[:].+/
  - label: 'documentation'
    branch:
      - /(documentation|doc|docs)[-/].+/
    title:
      - /(documentation|doc|docs)[:].+/  
    files:
      - '*.rst'
  - label: 'style'
    branch:
      - /(style)[-/].+/
    title:
      - /(style)[:].+/  
  - label: 'refactor'
    branch:
      - /(refactor)[-/].+/
    title:
      - /(refactor)[:].+/  
  - label: 'ci'
    branch:
      - /(ci)[-/].+/
    title:
      - /(ci)[:].+/  
  - label: 'chore'
    branch:
      - /(chore)[-/].+/
    title:
      - /(chore)[:].+/
  - label: 'refactor'
    branch:
      - /(refactor)[-/].+/
    title:
      - /(refactor)[:].+/
  - label: 'perf'
    branch:
      - /(perf|performance)[-/].+/
    title:
      - /(perf|performance)[:].+/
  - label: 'test'
    branch:
      - /(test|testing|tests)[-/].+/
    title:
      - /(test|testing|tests)[:].+/
  - label: 'build'
    branch:
      - /(build)[-/].+/
    title:
      - /(build)[:].+/
  - label: 'revert'
    branch:
      - /(revert)[-/].+/
    title:
      - /(revert)[:].+/
  - label: 'dependencies'
    branch:
      - /(dependencies|deps)[-/].+/
    title:
      - /(dependencies|deps)[:].+/
  - label: 'security'
    branch:
      - /(sec|security)[-/].+/
    title:
      - /(sec|security)[:].+/