---
# This playbook will clone a Git repository and move specified cached files
# If you are using an access token, you can specify it in the `git_server` URL
# For example: https://<token>@github.com/user/repo.git
# The user will need to provide all relevant information including:
# - ``git_server`` - The URL of the git server
# - ``git_repo_path`` - The path to the repo from the server
# - ``git_branch`` - The branch name (optional); default: main

- name: Clone Git repository and move files
  hosts: localhost
  vars_prompt:
    - name: git_server
      prompt: "Please enter the Git server URL or set `ansible.git_server` in the FIREWHEEL configuration."
      private: false

    - name: git_repo_path
      prompt: "Please enter the path to the git repository or set `ansible.git_repo_path` in the FIREWHEEL configuration."
      private: false

  tasks:
    - name: Clone the Git repository
      ansible.builtin.git:
        repo: "{{ git_server }}/{{ git_repo_path }}"
        dest: "/tmp/fwcache"
        version: "{{ git_branch | default(omit) }}"
        clone: true
        update: true
      register: git_clone_result

    - name: Move cached files to the desired location
      ansible.builtin.copy:
        src: "/tmp/fwcache/{{ item.source }}"
        dest: "{{ item.destination }}"
        mode: "666"
      loop: "{{ cached_files }}"

    - name: Remove the Git repository
      ansible.builtin.file:
        path: "/tmp/fwcache"
        state: absent
