---
- name: Check online status and manage cache retrieval
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Import variables from model component
      include_vars:
        file: "{{ vars_path }}"
    - name: Check for files
      include_role:
        name: firewheel
        tasks_from: check_and_end.yml

    - name: Adding git
      include_role:
        name: firewheel
        tasks_from: git.yml

    - name: Adding s3
      include_role:
        name: firewheel
        tasks_from: s3.yml
      when:
        - git_clone_result is not defined or git_clone_result is failed

    - name: Adding url
      include_role:
        name: firewheel
        tasks_from: url.yml
      when:
        - git_clone_result is not defined or git_clone_result is failed
        - s3_download_result is not defined or s3_download_result is failed

    # check_and_end (if we ran a cache)
    - name: Check for files
      include_role:
        name: firewheel
        tasks_from: check_and_end.yml
      when:
        - (git_clone_result is defined and git_clone_result is succeeded) or (s3_download_result is defined and s3_download_result is succeeded) or (url_download_result is defined and url_download_result is succeeded)

    - name: Check if user is online
      ansible.builtin.command: ping -c 1 8.8.8.8
      register: ping_result
      ignore_errors: true

    - name: Final failure message if all attempts fail
      ansible.builtin.fail:
        msg: "All cache file methods have failed and system does not appear to be online. Please provide valid cache information."
      when: ping_result.rc | default(0) != 0

    # We definitly don't have any cached files and are online
    # so we need to run the tasks
    - name: Include INSTALL tasks if online
      include_tasks: "{{ tasks_path }}"
      when: ping_result.rc | default(1) == 0

    - name: Check for files
      include_role:
        name: firewheel
        tasks_from: check_and_end.yml

    - name: Fail if any cached file destination does not exist
      ansible.builtin.fail:
        msg: "Failed to correctly install this model component!"
