name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.draft_release.outputs.tag_name }}
      release_notes: ${{ steps.draft_release.outputs.body }}
    steps:
      - name: Draft Release Notes
        id: draft_release
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
          disable-autolabeler: false
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr-checker:
    name: Ensure Proper Pull Request Labels
    if: ${{ always() }}
    needs: update_release_draft
    permissions:
      pull-requests: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@7145ecb81a69104f99767cb133bf856e749f7e73
        with:
          hasSome: feature,fix,style,changed,refactor,perf,test,build,ci,chore,revert,deprecated,removed,security,documentation,dependencies
          githubToken: ${{ secrets.GITHUB_TOKEN }}